### ISSUE TITLE
Error during installation using go installer

### ISSUE THREAD

**Issue by Karmaz95** [sensepost/gowitness#102] opened 2021-05-16 10:36 UTC
**Describe the bug**
Cannot install gowitness using go installer.

**To Reproduce**
1. Issue below request in terminal:
`❯ go get -u github.com/sensepost/gowitness`

**Expected behavior**
```
#github.com/sensepost/gowitness/chrome
../../go/src/github.com/sensepost/gowitness/chrome/chrome.go:177:28: assignment mismatch: 4 variables but page.GetLayoutMetrics().Do returns 7 values
```
**Version Information:**
 - OS: Linux Mint 
 - gowitness: 2.3.4

**Comment by leonjza** [comment] 2021-05-17 04:31
Thanks! Duplicate of #101

**Closed by leonjza** 2021-05-17 04:31 UTC
Labels: duplicate
