### ISSUE TITLE
[FEATURE] Export HTML report

### ISSUE THREAD

**Issue by random-robbie** [sensepost/gowitness#115] opened 2021-08-24 09:20 UTC
**Is your feature request related to a problem? Please describe.**
I would like to export the html report to a specific directory

**Describe the solution you'd like**
when running `gowitness report export -d output/`

**Describe alternatives you've considered**
I was thinking of either finding something that would capture the html from the report serve or aquatone.

**Comment by leonjza** [comment] 2021-08-24 10:00
duplicate of #93

**Closed by leonjza** 2021-08-24 10:00 UTC
Labels: duplicate
