### ISSUE TITLE
You can add an exclusion status code parameter to specify, -x 401,404,405 Excluded will not be screenshot 

### ISSUE THREAD

**Issue by r00tSe7en** [sensepost/gowitness#140] opened 2022-07-07 02:31 UTC
You can add an exclusion status code parameter to specify, -x 401,404,405 Excluded will not be screenshot

**Comment by leonjza** [comment] 2022-07-11 04:56
Duplicate of #133

**Closed by leonjza** 2022-07-11 04:56 UTC
Labels: duplicate
